# Quadrotor planning parameters
# MapTopic:                   "/fast_mapping/Voxel_map"
MapTopic:                   "/nanovoxmap/Voxel_map"
GroundTruthTopic:           "/quadrotor/ground_truth"
VelodynePoseTopic:          "/velodyne/ground_truth"
FilteredCloudTopic:         "/filtered_cloud"


## floorplan1_static.world
DeflationFactor:            0.0
VoxelResolution:            0.9
FilterRadius:               0.5
MapLowerBound:              [-20.0, -10.0, -0.3]
MapUpperBound:              [20.0, 10.0, 2.2]
InitialPose:                [0.0, 0.0, 0.02]
GoalPose:                   [0.0, 0.0, 1.0]
DmPotentialRadius:          [1.0, 1.0, 1.0]
DmPSearchRadius:            [2.0, 2.0, 2.0]
horizon:                    6
