# MapTopic:                   "/nanovoxmap/Voxel_map"
MapTopic:                   "/occupancy_inflation/inflated_cloud"
GroundTruthTopic:           "/quadrotor/ground_truth"
VelodynePoseTopic:          "/velodyne/ground_truth"
FilteredCloudTopic:         "/filtered_cloud"


# floorplan1_static.world
VoxelResolution:            0.25
FilterRadius:               0.0
MapLowerBound:              [-20.0, -10.0, -0.3]
MapUpperBound:              [20.0, 10.0, 2.2]
InitialPose:                [0.0, 0.0, 0.02]
GoalPose:                   [0.0, 0.0, 1.0]
DmPotentialRadius:          [1.0, 1.0, 1.0]
DmPSearchRadius:            [2.0, 2.0, 2.0]
horizon:                    6